export const LOGISTICS = [
    {
        id: 1,
        name: "Wildberries",
        place: "Чехов",
        price: 430,
        per: "за 1 коробку",
        applied: false,
    },
    {
        id: 2,
        name: "Wildberries",
        place: "Электросталь",
        price: 430,
        per: "за 1 коробку",
        applied: false,
    },
    {
        id: 3,
        name: "Wildberries",
        place: "Подольск",
        price: 430,
        per: "за 1 коробку",
        applied: false,
    },
    {
        id: 4,
        name: "Wildberries",
        place: "Домодедово",
        price: 340,
        per: "за 1 коробку",
        applied: false,
    },
    {
        id: 5,
        name: "Wildberries",
        place: "Пушкино",
        price: 430,
        per: "за 1 коробку",
        applied: false,
    },
    {
        id: 6,
        name: "Wildberries",
        place: "Вешки",
        price: 430,
        per: "за 1 коробку",
        applied: false,
    },
    {
        id: 7,
        name: "OZON",
        place: "Хоругвино",
        price: 430,
        per: "за 1 коробку",
        applied: false,
    },
    {
        id: 8,
        name: "OZON",
        place: "Пушкино",
        price: 430,
        per: "за 1 коробку",
        applied: false,
    },
    {
        id: 9,
        name: "OZON",
        place: "Жуковский",
        price: 320,
        per: "за 1 коробку",
        applied: false,
    },
    {
        id: 10,
        name: "OZON",
        place: "Петровское",
        price: 430,
        per: "за 1 коробку",
        applied: false,
    },
    {
        id: 11,
        name: "OZON",
        place: "Павловская Слобода",
        price: 430,
        per: "за 1 коробку",
        applied: false,
    },
];
